
DROP TABLE "ORGDA1"."ORG_DEPARTMENT";
create table ORGDA1.ORG_DEPARTMENT
(
   ID                   NVARCHAR2(20)        not null,
   NAME_CN              NVARCHAR2(100),
   NAME_EN              NVARCHAR2(100),
   CODE                 NVARCHAR2(100),
   COST_CENTER_CODE     NVARCHAR2(100),
   DEPT_LEVEL   NUMBER,
   PID                  NVARCHAR2(100),
   DIRECTOR             NVARCHAR2(100),
   ASSISTANT            NVARCHAR2(100),
   AD_GROUP_NAME        NVARCHAR2(100),
   IS_INVALID           NVARCHAR2(1),
   IS_HIDDEN            NVARCHAR2(1),
   CODE_CURRENT         NVARCHAR2(100),
   DISPLAYNAME          NVARCHAR2(100),
   PINYIN               NVARCHAR2(200),
   DISABLE_DATE         TIMESTAMP,
   EMAIL                NVARCHAR2(300),
   constraint PK_DEPT_ID primary key (ID)

);

COMMENT ON COLUMN "ORGDA1"."DEPT"."ID" IS 'ID';

COMMENT ON COLUMN "ORGDA1"."DEPT"."NAME_CN" IS '中文';

COMMENT ON COLUMN "ORGDA1"."DEPT"."NAME_EN" IS '英文';

COMMENT ON COLUMN "ORGDA1"."DEPT"."CODE" IS '组织编码';

COMMENT ON COLUMN "ORGDA1"."DEPT"."COST_CENTER_CODE" IS '成本中心代码';

COMMENT ON COLUMN "ORGDA1"."DEPT"."DEPT_LEVEL" IS '组织等级';

COMMENT ON COLUMN "ORGDA1"."DEPT"."PID" IS '上级ID';

COMMENT ON COLUMN "ORGDA1"."DEPT"."DIRECTOR" IS '描述';

COMMENT ON COLUMN "ORGDA1"."DEPT"."ASSISTANT" IS '主管';

COMMENT ON COLUMN "ORGDA1"."DEPT"."AD_GROUP_NAME" IS 'AD群组';

COMMENT ON COLUMN "ORGDA1"."DEPT"."IS_INVALID" IS '是否无效（N/Y)';

COMMENT ON COLUMN "ORGDA1"."DEPT"."IS_HIDDEN" IS '是否隐藏 （N/Y)';

COMMENT ON COLUMN "ORGDA1"."DEPT"."CODE_CURRENT" IS '当前组织编码（包含上级）';

COMMENT ON COLUMN "ORGDA1"."DEPT"."DISPLAYNAME" IS '中文显示名称';

COMMENT ON COLUMN "ORGDA1"."DEPT"."PINYIN" IS '英文显示名称';

COMMENT ON COLUMN "ORGDA1"."DEPT"."DISABLE_DATE" IS '失效日期';

COMMENT ON COLUMN "ORGDA1"."DEPT"."EMAIL" IS '邮件';




DROP TABLE "ORGDA1"."ORG_EMPLOYEE";
CREATE TABLE "ORGDA1"."ORG_EMPLOYEE" (
  "ID" NVARCHAR2(100) NOT NULL,
  "JOB_NUMBER" NVARCHAR2(50),
  "NAME_CN" NVARCHAR2(200),
  "NAME_EN" NVARCHAR2(200),
  "FIRST_NAME" NVARCHAR2(200),
  "LAST_NAME" NVARCHAR2(200),
  "MIDDLE_NAME" NVARCHAR2(200),
  "EMP_CATEGORY" NVARCHAR2(100),
  "ON_BOARD_DATE" TIMESTAMP(6),
  "JOB_LEVEL" NVARCHAR2(100),
  "DEPT_ID" NVARCHAR2(20),
  "WORK_LOCATION_ID" NVARCHAR2(20),
  "LOCATION" NVARCHAR2(200),
  "EXTENSION" NVARCHAR2(30),
  "FAX_EXTENSION" NVARCHAR2(30),
  "DIRECT_LINE" NVARCHAR2(30),
  "DIRECT_FAX" NVARCHAR2(30),
  "CELL_PHONE" NVARCHAR2(30),
  "PHS" NVARCHAR2(30),
  "EMAIL" NVARCHAR2(50),
  "NOTES_ID_NAME" NVARCHAR2(500),
  "IS_HIDDEN" NVARCHAR2(1) DEFAULT 'N',
  "DIRECT_SUPERVISOR" NVARCHAR2(100),
  "SECRETARY" NVARCHAR2(50),
  "OUT_OF_OFFICE" NVARCHAR2(1),
  "PROXY" NVARCHAR2(50),
  "IS_INVALID" NVARCHAR2(1) DEFAULT 'N',
  "PINYIN" NVARCHAR2(100),
  "REGIONAL_TYPE" NVARCHAR2(50),
  "DISPLAY_NAME" NVARCHAR2(100),
  "VOIP_EXTENSION" NVARCHAR2(20),
  "GROUP_ID" NVARCHAR2(100),
  "EMP_CARD" NVARCHAR2(100),
  "PHOTO" BLOB,
  "PART_DEPT_ID" NVARCHAR2(20)

);
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."ID" IS 'ID';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."JOB_NUMBER" IS '工号';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."NAME_CN" IS '姓名 （cn）';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."NAME_EN" IS '姓名 （en）';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."FIRST_NAME" IS '名字';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."LAST_NAME" IS '姓氏';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."MIDDLE_NAME" IS 'middle name（中间名字）';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."EMP_CATEGORY" IS '员工类型';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."ON_BOARD_DATE" IS '入职日期';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."JOB_LEVEL" IS '岗位（人员）等级';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."DEPT_ID" IS '所属组织';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."WORK_LOCATION_ID" IS '工作地点';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."LOCATION" IS '工作区域';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."EXTENSION" IS '分机号码';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."FAX_EXTENSION" IS '传真分机';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."DIRECT_LINE" IS '直线电话';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."DIRECT_FAX" IS '传真电话';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."CELL_PHONE" IS '手机号';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."PHS" IS '个人电话';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."NOTES_ID_NAME" IS '签名';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."IS_HIDDEN" IS '是否隐藏 （Y/N）';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."DIRECT_SUPERVISOR" IS '直接主管';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."SECRETARY" IS '秘书/部长';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."OUT_OF_OFFICE" IS '在外办工';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."PROXY" IS '代理人';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."IS_INVALID" IS '是否在职 （Y/N）';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."PINYIN" IS '姓名拼音';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."REGIONAL_TYPE" IS '区域类型';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."DISPLAY_NAME" IS '显示名称';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."VOIP_EXTENSION" IS '分机区号-分机号码：VOIP_EXTENSION';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."GROUP_ID" IS '群组';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."EMP_CARD" IS '工卡';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."PHOTO" IS '照片';
COMMENT ON COLUMN "ORGDA1"."ORG_EMPLOYEE"."PART_DEPT_ID" IS '上级组织';





